[package]
name = "pacewright-cli"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "pacewright"
path = "src/main.rs"

[dependencies]
pacewright-proto = { path = "../proto" }
pacewright-adapter-recipe = { path = "../adapter-recipe" }
pacewright-core = { path = "../core" }
pacewright-adapter-agent = { path = "../adapter-agent" }
reqwest.workspace = true
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
clap.workspace = true
ratatui.workspace = true
crossterm.workspace = true
chrono.workspace = true
kdl.workspace = true
toml.workspace = true
uuid.workspace = true
serde = { workspace = true }
